# Generated by Django 3.0.4 on 2020-03-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200328_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
