# Generated by Django 3.0.4 on 2020-03-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='project_name',
        ),
    ]
