# Generated by Django 3.0.4 on 2020-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_pictures_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='image_2',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
