# Generated by Django 3.0.4 on 2020-03-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200329_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='pictures',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Projects'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
