# Generated by Django 3.0.4 on 2020-03-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200329_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='presentation',
        ),
    ]
