# Generated by Django 3.0.4 on 2020-03-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_pictures_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='presentation',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=6),
        ),
    ]
