# Generated by Django 3.0.4 on 2020-03-29 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200329_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='presentation',
            field=models.CharField(choices=[('slide', 'Slide'), ('picture', 'Picture'), ('project', 'Project'), ('album', 'Album')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Published Date'),
        ),
    ]
