# Generated by Django 3.0.4 on 2020-03-29 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200329_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Projects'),
        ),
    ]
